server: 
  port: 8081 

spring:
  application:
    name: tpi-2025-grupo12-logistica
  datasource:
    url: jdbc:h2:file:./data/tpiDb-logistica
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always

springdoc: 
  swagger-ui: 
    path: /swagger-ui.html 

google: 
  maps: 
    apikey: AIzaSyDAXcMocfHcz1ipvHOYP4L9iBqTfw9VroE

servicio:
  ciudades:
    url: http://localhost:8080/api/pedidos