spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/tpi-backend

  cloud:
    gateway:
      routes:
        - id: pedidos-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=2

        - id: logistica-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/logistica/**
          filters:
            - StripPrefix=2
  
      
server:
  port: 8082

seguridad:
  desactivada: true

